# Generated by Django 2.0.4 on 2018-04-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilelinkgenerator', '0002_auto_20180420_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urltokens',
            name='token',
            field=models.TextField(default=''),
        ),
    ]
