# Generated by Django 2.0.4 on 2018-04-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilelinkgenerator', '0003_auto_20180420_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urltokens',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='urltokens',
            name='token',
            field=models.TextField(),
        ),
    ]
