# Generated by Django 2.0.4 on 2018-04-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_email', models.EmailField(max_length=254)),
                ('score', models.IntegerField()),
                ('event_id', models.IntegerField()),
            ],
        ),
    ]
