# Generated by Django 2.0.4 on 2018-04-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email_address',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
