# Generated by Django 2.0.4 on 2018-04-18 16:03

from django.db import migrations, models
import signupmanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('signupmanager', '0002_auto_20180418_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='animal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='education',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='environment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='userdata',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='medical',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to=signupmanager.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='userdata',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
