# Generated by Django 2.0.4 on 2018-04-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupmanager', '0003_auto_20180418_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='gender',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
