# Generated by Django 2.0.4 on 2018-04-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupmanager', '0005_auto_20180418_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='last_name',
        ),
    ]
