# Generated by Django 2.0.4 on 2018-04-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupmanager', '0008_auto_20180418_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='score',
        ),
    ]
