# Generated by Django 2.0.4 on 2018-04-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupmanager', '0010_auto_20180418_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='gender',
            field=models.CharField(default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='userdata',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='profile_photo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
