# Generated by Django 2.0.4 on 2018-04-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupmanager', '0014_auto_20180419_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profile_link',
            field=models.TextField(null=True),
        ),
    ]
