# Generated by Django 2.0.4 on 2018-04-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupmanager', '0015_auto_20180419_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profile_link',
            field=models.TextField(blank=True),
        ),
    ]
