# Generated by Django 2.0.4 on 2018-04-18 17:06
from django.db import migrations, models
class Migration(migrations.Migration):
    initial = True
    dependencies = [
    ]
    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(max_length=50)),
                ('host_email', models.CharField(max_length=320)),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('score', models.IntegerField()),
                ('volunteers_required', models.IntegerField()),
            ],
        ),
    ]
