# Generated by Django 2.0.4 on 2018-04-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcomingevents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='event_name',
        ),
        migrations.AddField(
            model_name='event',
            name='hours_per_day',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='event',
            name='no_of_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='volunteers_registered',
            field=models.IntegerField(default=0),
        ),
    ]
