# Generated by Django 2.0.4 on 2018-04-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_title', models.CharField(max_length=200)),
                ('donation_item_description', models.CharField(max_length=1000)),
                ('ngo_name', models.CharField(max_length=200)),
                ('ngo_email', models.CharField(max_length=320)),
                ('location', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
    ]
